# -*- coding: utf-8 -*-
from .official_odoo_inh import auth_signup
from .official_odoo_inh import res_users
from . import tt_frontend_security
from . import tt_history
from .official_odoo_inh import res_country
from . import address_detail
from . import phone_detail
from . import social_media_detail
from . import payment_acquirer
from . import agent_bank_detail
from . import customer_bank_detail
from . import tt_access_activity
from . import tt_bank
from .official_odoo_inh import res_currency
from . import res_rate
from . import res_social_media_type
from . import tt_employee
from . import tt_provider
from . import tt_customer_job_position
from . import tt_customer
from . import tt_agent_type
from . import tt_agent
from . import tt_destinations
from . import transport_carrier
from . import tt_transport_carrier_search
from . import tt_routes
from . import tt_provider_type
from . import tt_customer_parent
from . import tt_customer_parent_type
from . import tt_customer_parent_booker_rel
from . import tt_osi_corporate_code
from . import error_api
from . import tt_ssr
from . import tt_cabin_class
from . import tt_product_class
from . import tt_fare_rules
from . import tt_cron_log
from . import tt_upload_center
from . import tt_ban_user
from . import tt_pnr_quota
from . import tt_pnr_quota_usage
from . import tt_pnr_quota_price_list
from . import tt_pnr_quota_price_package
from . import tt_email_queue
from . import tt_vendor
from . import tt_loyalty_program
from . import tt_public_holiday
from . import tt_letter_guarantee
from .official_odoo_inh import ir_mail_server
from .official_odoo_inh import mail_mail
from .official_odoo_inh import ir_exports
from .official_odoo_inh import ir_filters
from . import tt_agent_notification
from . import tt_otp
from . import tt_pin_log
