# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'tt_reservation_airline',
    'version' : 'beta',
    'summary': 'Transport Reservation Airline',
    'sequence': 2,
    'description': """
TT_TRANSPORT
""",
    'category': 'booking',
    'website': '',
    'images' : [],
    'depends' : ['base_setup','tt_base','tt_reservation','base_address_city','tt_in_api_connector'],
    'data': [
        'views/menu_item_base.xml',

        'wizard/tt_split_reservation_wizard.xml',
        'wizard/tt_get_booking_from_vendor.xml',

        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/tt_provider_type_data.xml',
        'data/tt_provider_airline.xml',
        'data/tt_destination_airline.xml',
        'data/tt_transport_carrier_airline.xml',
        'data/tt_transport_carrier_type_airline.xml',
        'data/tt_transport_carrier_search_airline.xml',
        'data/tt_psg_limiter_rule_data.xml',
        'data/ir_send_email.xml',
        'data/tt_loyalty_program_data.xml',
        'data/tt_frequent_flyer_airline_data.xml',
        'data/tt_pnr_quota_price_list_airline_data.xml',
        'data/tt_pricing_agent_airline_data.xml',

        # 'data/test_destination/tt_destination_airline_26_feb_2020_0.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_1.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_2.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_3.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_4.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_5.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_6.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_7.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_8.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_9.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_10.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_11.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_12.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_13.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_14.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_15.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_16.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_17.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_18.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_19.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_20.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_21.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_22.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_23.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_24.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_25.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_26.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_27.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_28.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_29.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_30.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_31.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_32.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_33.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_34.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_35.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_36.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_37.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_38.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_39.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_40.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_41.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_42.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_43.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_44.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_45.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_46.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_47.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_48.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_49.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_50.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_51.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_52.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_53.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_54.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_55.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_56.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_57.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_58.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_59.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_60.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_61.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_62.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_63.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_64.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_65.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_66.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_67.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_68.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_69.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_70.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_71.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_72.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_73.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_74.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_75.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_76.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_77.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_78.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_79.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_80.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_81.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_82.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_83.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_84.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_85.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_86.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_87.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_88.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_89.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_90.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_91.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_92.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_93.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_94.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_95.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_96.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_97.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_98.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_99.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_100.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_101.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_102.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_103.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_104.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_105.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_106.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_107.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_108.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_109.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_110.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_111.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_112.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_113.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_114.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_115.xml',
        # 'data/test_destination/tt_destination_airline_26_feb_2020_116.xml',

        # 'data/tt_cabin_class.xml',
        # 'data/tt_product_class.xml',
        'security/ir.model.access.csv',
        'security/ir_rule_data.xml',

        'wizard/force_issued_wizard_views.xml',

        'views/tt_reservation_airline.xml',
        'views/tt_provider_views.xml',
        'views/tt_journey_views.xml',
        'views/tt_segment_views.xml',
        'views/tt_leg_views.xml',
        'views/tt_service_charge_views.xml',
        'views/tt_segment_addons_views.xml',
        'views/tt_fee_airline_views.xml',
        'views/tt_reservation_passenger_airline_form_views.xml',
        'views/tt_promo_code_airline_views.xml',
        'views/tt_frequent_flyer_airline_views.xml',
        'views/tt_ff_passenger_airline_views.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
