from . import tt_service_charge_airline
from . import tt_journey_airline
from . import tt_provider_airline
from . import tt_ticket_airline
from . import tt_segment_airline
from . import tt_leg_airline
from . import tt_reservation_airline
from . import tt_seat_airline
from . import tt_reservation_passenger_airline