from . import tt_reservation_lab_pintar
from . import tt_provider_lab_pintar
from . import tt_reservation_passenger_lab_pintar
from . import tt_timeslot_lab_pintar
from . import tt_service_charge_lab_pintar
from . import tt_analyst_lab_pintar
from . import tt_ticket_lab_pintar
from . import tt_price_list_lab_pintar
from . import tt_cron_log
